name: Development Build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
  - cron: "*/15 * * * *"

jobs:
  android_build:
    type: build
    params:
      platform: android
      profile: development

  ios_build:
    type: build
    params:
      platform: ios
      profile: development